# Generated by Django 3.1.4 on 2021-07-21 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_time', models.IntegerField(help_text='***Enter time in mins')),
                ('teaching_time', models.IntegerField(help_text='***Enter time in mins')),
                ('questions_time', models.IntegerField(help_text='***Enter time in mins')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ('-config_id',),
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=30, unique=True)),
                ('std_description', models.TextField()),
                ('std_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standards',
                'ordering': ('std_id',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=40)),
                ('sub_description', models.TextField()),
                ('sub_created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTApp.standard')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('sub_name',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_description', models.TextField()),
                ('topic_created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTApp.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('topic_name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=15)),
                ('sec_description', models.TextField()),
                ('sec_created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTApp.standard')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('-standard',),
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=45)),
                ('topic', models.CharField(max_length=100)),
                ('total_time', models.IntegerField()),
                ('teaching', models.IntegerField()),
                ('questioning', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ('-created_at',),
            },
        ),
    ]
