# Generated by Django 3.1.4 on 2021-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='questioning',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='teaching',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='total_time',
            field=models.IntegerField(null=True),
        ),
    ]
