# Generated by Django 3.1.4 on 2021-07-23 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RTApp', '0002_auto_20210721_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=45)),
                ('topic', models.CharField(max_length=100)),
                ('total_time', models.IntegerField(null=True)),
                ('teaching', models.IntegerField(null=True)),
                ('questioning', models.IntegerField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ('-created_at',),
            },
        ),
    ]
